image: node:alpine

stages:
  - install
  - test
  - build

install:
  stage: install
  script:
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
  cache:
    paths:
      - node_modules

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: build
  script:
    - npm run build
